### ISSUE TITLE
Expected to see an error but no error shows up in Lab 04  Exercise 1 Task 6 but no error shows up.

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/MS-203T00-Microsoft-365-Messaging#127]
# Lab/Demo: 04
#### Step: 38

Description of issue

An error does not show up as stated in the instruction

![image](https://user-images.githubusercontent.com/98971092/211587852-35354dc9-1b39-42af-9cbf-9d09906aa578.png)

Email has been sent as well to Alex Wilber

![image](https://user-images.githubusercontent.com/98971092/211588881-afcbad64-d251-4881-9126-a2976f98fc8a.png)

Can I get any help in this regard? 

Thank you.

Repro steps:

1. Perform all the steps till 38
2.  Expected to see an error but no error showed up.

**Comment by maquinl** [comment]
@Kiyani1 - I can confirm after testing this behavior extensively that error messages are no longer displayed. 

Because Nestor (the admin in question within the exercise) does not have appropriate permissions to view message samples for content searches in an eDiscovery case (not part of eDiscovery Management role group), no preview messages appear. This is now expected behavior.

I will update the lab instructions to reflect the new UI experience. Thanks for the feedback!
